'use strict';

const { commentIssue } = require('../../lib/github');
const translate = require('../../lib/translate');

function containsChinese(title) {
  return /[\u4e00-\u9fa5]/.test(title);
}

function replyTranslate(on) {
  on('issues_opened', ({ payload }) => {
    let content = `
Translation of this issue:

<hr/>

## ${payload.issue.title}

${payload.issue.body}
`;

    async function translateFn() {
      if (containsChinese(payload.issue.title)) {
        content = content.replace('<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->', '');
        try {
          const res = await translate(content, { from: 'zh-CN', to: 'en' });
          commentIssue({
            owner: payload.repository.owner.login,
            repo: payload.repository.name,
            number: payload.issue.number,
            body: res.text,
          });
        } catch (err) {
          console.error(err);
        }
      }
    }

    translateFn().catch(err => console.error(err.stack));
  });
}

module.exports = replyTranslate;

